on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

name: Go
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Go
      id: go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
        check-latest: true
    - name: Vet
      run: go vet ./...
    - name: Test
      run: go test ./...
